### PR TITLE
Add INSTALL section to README

### LINKED ISSUE #27: Add install section to readme
Heard about `jack_capture` from https://community.blokas.io/t/solved-capturing-modep-output-with-jack-capture/300 and as a new user was scanning for Install section on readme. I may yet find it but as a new user looking for install instructions they are not easy to see in first 1 minute.

### PR DESCRIPTION
**Pull request by ElijahLynn**
Fixes #27.

### CODE REVIEW

**Comment by kmatheussen** [comment]
I don't think this is needed. Standard way to install a program is to write "make install".

**Comment by ElijahLynn** [comment]
> I don't think this is needed. Standard way to install a program is to write "make install".

This may be in your world, but it is not the world of everyone else.

**Comment by trebmuh** [comment]
FWIW, I agree that it would be great to have the installation information in the README as a common practice.

**Comment by kmatheussen** [comment]
Sure, I would accept a plain INSTALL paragraph in the README file that only
contains the line "make install"

**Comment by kmatheussen** [comment]
On Tue, Aug 20, 2019 at 5:01 PM Elijah Lynn <notifications@github.com>
wrote:

> I don't think this is needed. Standard way to install a program is to
> write "make install".
>
> This may be in your world, but it is not the world of everyone else.
>
>
Maybe you confuse install instructions with build instructions?

**Comment by kmatheussen** [comment]
Also, the README file doesn't contain build instructions either. That's
more important than install instructions.

**Comment by ElijahLynn** [comment]
I think the big picture here is that until this package is easily installable with many package managers, e.g. apt, pacman, yum, then some are going to be trying to install this from source, like myself. 

So, I am coming from a world where I don't build/install these types of programs much, and I understand that it may not fit the level where development is at.

This package is fantastic and I was able to use it to record directly from my Pisound sound card. I am using it as a musician in this case, not a developer.  I just wanted to paint a picture of other consumers of this package, like musicians who are tinkering with a Pisound.

**Comment by ElijahLynn** [comment]
Putting some notes here for the internet:

Am going through this install of `jack_capture` on a new system (Raspbian + PiSound) and ran into `fatal error: sndfile.h: No such file or directory` on the `make` and did an `apt search sndfile` and found that `libsndfile1` was already installed, after some more reading, I tried `apt install libsndfile1-dev` and that resolved this error. 

Now I am stuck on:
```
collect2: error: ld returned 1 exit status
make: *** [Makefile:63: jack_capture] Error 1
```

**Full Log**
```
patch@patchbox:~/jack_capture $ sudo make

Checking dependencies: 
which bash
/usr/bin/bash
which tr
/usr/bin/tr
which sed
/usr/bin/sed
which install
/usr/bin/install
which pkg-config
/usr/bin/pkg-config
which gcc
/usr/bin/gcc
which g++
/usr/bin/g++
gcc -I/opt/local/include -E testsndfile.c >/dev/null
All seems good 

bash gen_setformat_c.sh >setformat.c
bash gen_das_config_h.sh >das_config.h

jack_capture was configured with the following options:
------------------------------
#define HAVE_OGG 1
#define HAVE_LAME 0
#define HAVE_LIBLO 1
//COMPILEFLAGS  -llo -lpthread
#define NEW_JACK_LATENCY_API 1
------------------------------

cat das_config.h |grep COMPILEFLAGS|sed s/\\/\\/COMPILEFLAGS//|tr '\n' ' ' >config_flags
gcc -I/opt/local/include -O3 -DVERSION=\"0.9.73\" -Wall -Wextra -Wno-unused jack_capture.c vringbuffer.c upwaker.c osc.c -o jack_capture  -ljack -lsndfile -lm -lpthread -lrt `cat config_flags`
jack_capture.c: In function ‘init_arguments’:
jack_capture.c:2468:31: warning: ‘.’ directive output of 1 bytes causes result to exceed ‘INT_MAX’ [-Wformat-overflow=]
  sprintf(base_filename,"%s%0*d.%s",filename_prefix,leading_zeros+1,++try,soundfile_format);
                               ^
/usr/bin/ld: /tmp/ccqeJLVk.o: in function `print_console':
jack_capture.c:(.text+0x1a0): undefined reference to `__atomic_load_8'
/usr/bin/ld: /tmp/ccqeJLVk.o: in function `process':
jack_capture.c:(.text+0x142c): undefined reference to `__atomic_load_8'
/usr/bin/ld: jack_capture.c:(.text+0x1464): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: jack_capture.c:(.text+0x1470): undefined reference to `__atomic_load_8'
/usr/bin/ld: jack_capture.c:(.text+0x1500): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: jack_capture.c:(.text+0x1584): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make: *** [Makefile:63: jack_capture] Error 1
(reverse-i-search)`libs': sudo apt install libsndfile1-dev
```

**Comment by ElijahLynn** [comment]
> Now I am working through this error:
> 
> ```
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:63: jack_capture] Error 1
> ```

I fixed this in https://github.com/kmatheussen/jack_capture/pull/38.

**Pull request closed without merging**
